worker_processes auto;
events { worker_connections 1024; }
http {
  include /etc/nginx/mime.types;
  gzip on;
  gzip_types text/css application/javascript image/svg+xml;
  include /etc/nginx/conf.d/*.conf;
}
